global DEFAULT_TTL;
global DEFAULT_TTL_BACKOFF;
global DEFAULT_RANGE;
global DEFAULT_PACKET_SIZE;
global DEFAULT_CACHE_SIZE;
global DEFAULT_RRD;
global DEFAULT_RELAY_PROBABILITY;

DEFAULT_TTL=127;
DEFAULT_TTL_BACKOFF=0;
DEFAULT_RANGE=15;
DEFAULT_PACKET_SIZE=31;
DEFAULT_CACHE_SIZE=1001;
DEFAULT_RRD=20;
DEFAULT_RELAY_PROBABILITY=0.8;